language: python
python:
- '2.7'
install:
- pip install pycodestyle
script:
- pycodestyle kivmob.py
deploy:
  provider: pypi
  user: mstott6
  on:
    branch: master
  password:
    secure: Ox+WqfVcX4iYWsouteBb+BsiB+QFdJT6bEXHhFHFsvZs+wtE0cx9GPSOthRX7VLNtSSzssC1pAIQnyO+S7IyP2eyOpNEkI9g0/KB1qZ8BGY++MeFN7xw8nPtYHel8kxR6SHRayjJXJyklC8utM5GwO7HdLCR9R+00Dk/jOhrmCW9J7uft3bTGhLagRBTi9mibTkVGV1D00J9rwPUfVJV/drT2bbVbyxCDUK7KJp6CVLTMXhMbkk2MLBc6CHi4ihsTJCQN5751IeAXgJQGJzGVzXFuA0CERVf0JAm3GSpvVIH5+/duNE2U7U1Zwp3KBpU6unyM7IvoSOjIYDKXEo5D0YafWOou9X435+nKeSb5y6ttJuHNFjHqw4JsHTdLU1VV04cwC7cB3HzVcsa496qDIneinCQbq76isFEVgaKOPL6BRRQoCC9oUOXpbOnxA4vCujyMDCaz/0sX8CCWGI+ESJFva2MEHAOXTChPiz1BTIjjcpicq/MQAa9kLRFxxPBRTWRmNg46ZfsRT2PZ1uoXD5l2wwf0cnlZiilxwMFtDqRV+tXvM+8QjO22D6IWoGLk2CjSpW3ELsp8HHuVpGYwgjCUXJOy5sqQHUYMl/gBhYSh5wOy04jxsr5SlFPhfGbpA/PrYSZ7NVYtlMqqns/K182a5OiYJ9VF9nEfPpVHaw=
